language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq mono-complete

script:
  - cd client
  - mvn -q clean install
  - cd ../dotNet
  - ./compile.sh
  - cd ../j2e
  - mvn -q clean package
  - cd ..

after_script:
  - cd dotNet
  - nohup mono server.exe /standalone &
  - cd ../j2e
  - mvn package -Dtest=PaymentIntegrationTest
  - rm ../dotNet/server.LOCK

deploy:
  provider: script
  script:
    - cd docker
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - cd client ; ./build.sh ; ./publish.sh
    - cd ../partners ; ./build.sh ; ./publish.sh
    - cd ../tcf ; ./build.sh ; ./publish.sh
    - cd ..

notifications:
  email:
    recipients:
      - sebastien.mosser@gmail.com
